import Link from "next/link";
import Head from "next/head";
import styled from "styled-components";
import { useContext, useEffect, useState } from "react";
import { useRouter } from "next/router";
import userContext from "../Context/context";
import Image from "next/image";

const HeaderWrapper = styled.div`
  width: 100vw;
  height: 12vh;
  background-color: #f5f5f5;
  position: fixed;
  top: 0;
  z-index: 1000;
  font-size: 15px;
`;

const MainHeader = styled.div`
  padding: 0.75rem 2rem;
  display: flex;
  justify-content: space-between;
`;

const NavList = styled.ul`
  display: flex;
  justify-content: space-between;
  list-style: none;
`;

const NavLinks = styled.li`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  padding-right: 20px;
`;

function Header() {
  const [tokenExist, setTokenExist] = useState(false);
  const [LoggedInUser, setLoggedInUser] = useState(null);
  const { userData, logout } = useContext(userContext);
  const router = useRouter();
  const {push} = router;
  // router.reload(window.location.pathname);

  useEffect(() => {
    const token = sessionStorage.getItem("Token");
    if (token) {
      const sessionUser = sessionStorage.getItem("User");
      const user = JSON.parse(sessionUser);
      setTokenExist(true);
      setLoggedInUser(user);
    } else setTokenExist(false);
  }, [userData]);

  // console.log(LoggedInUser);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderWrapper>
        <MainHeader>
          <Link href={"/"} passHref>
            <a className="navbar-brand" href="#">
              Navbar
            </a>
          </Link>
          <NavList>
            <NavLinks>
              <i className="bi bi-star"></i>
              <Link href="/latestmovies" passHref>
                <a className="nav-link">Latest Movies</a>
              </Link>
            </NavLinks>
            <NavLinks>
              <i className="bi bi-camera-reels"></i>
              <Link href="/mostpopular" passHref>
                <a className="nav-link">Most Popular Movies</a>
              </Link>
            </NavLinks>
            <NavLinks>
              <i className="bi bi-film"></i>
              <Link href="/topmovies" passHref>
                <a className="nav-link">Top Movies</a>
              </Link>
            </NavLinks>
          </NavList>

          {!tokenExist ? (
            <NavList>
              <NavLinks>
                <Link href="/account/sign-in">Sign In</Link>
              </NavLinks>
              <NavLinks>
                <Link href="/account/sign-up">Sign Up</Link>
              </NavLinks>
            </NavList>
          ) : (
            <NavList>
              <NavLinks>
                <Link href="/account/profile" passHref>
                  <Image
                    src={LoggedInUser.photoURL}
                    alt={"Profile-picture"}
                    width={40}
                    height={40}
                    style={{ borderRadius: "50%" }}
                  />
                </Link>
              </NavLinks>
              <NavLinks>
                <button onClick={() => logout(push("/"))}>Sign out</button>
              </NavLinks>
            </NavList>
          )}
        </MainHeader>
      </HeaderWrapper>
    </>
  );
}

export default Header;
