import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import '../src/config/firebase.config';
import { useRouter } from "next/router";

export default function Home() {
  const brandImages = [
    {name: "/../public/netflix.jpeg"},
   {name: "/../public/dw.jpeg"},
   { name: "/../public/mgm.jpeg"},
    {name: "/../public/rocky.jpeg"},
    {name: "/../public/universal.jpeg"},
    {name: "/../public/wb.jpeg"},
    {name: "/../public/sony.png"},
    {name: "/../public/paramount.png"},
  ];

  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="py-4">
      <div className="px-4 my-5 py-5 h-100">
        <div className="d-md-flex justify-content-md-between flex-xs-column">
          <div className="w-100 w-md-50">
            <h1 className="fs-1 mt-5 pt-5">Leave What to Watch To US</h1>
            <p className="fs-5">
              Lorem Ipsum has been the industry&apos;s standard dummy text ever
              since the 1500s, when an unknown printer took a galley of type and
              scrambled it to make a type specimen book. It has survived not
              only five centuries.
            </p>
            <button type="button" className="btn btn-primary" onClick={()=>router.push('/latestmovies')}>
              Explore
            </button>
          </div>
          <Image
            src={"/../public/movi-app-removebg-preview.png"}
            alt={"Movie-img"}
            width={800}
            height={600}
          />
        </div>
        <div>
        </div>
      </div>
      <h2 className="text-center py-4 mb-3">Movie Brands That Trust Us</h2>
          <div className="d-flex flex-wrap justify-content-between mx-auto">
            {brandImages.map((m)=>{
              return <Image src={m.name} key={m.name} alt={m.name} width={305} height={250}/>
            })}
          </div>
    </div>
    </div>
  );
}
