import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import styles from "../styles/Home.module.css";
import "../src/config/firebase.config";
import { useRouter } from "next/router";
import Netflix from "../public/netflix.jpeg";
import DW from "../public/dw.jpeg";
import MGM from "../public/mgm.jpeg";
import Rocky from "../public/rocky.jpeg";
import Universal from "../public/universal.jpeg";
import WB from "../public/wb.jpeg";
import Sony from "../public/sony.png";
import Paramount from "../public/paramount.png";
import Laptop from "../public/movi-app-removebg-preview.png";
import { useState } from "react";

const SearchSection = styled.div`
  height: 10rem;
  display: flex;
  justify-content: space-evenly;
  align-items: center;
  font-family: Zen Kaku Gothic New, sans-serif;
  background-image: linear-gradient(
    to left bottom,
    #3c762f,
    #54822a,
    #6e8e23,
    #8a991a,
    #a8a311
  );

  @media only screen and (max-width: 600px) {
    flex-direction: column;
    padding: 1rem 0 2rem;
  }
`;
const Input = styled.input`
  padding: 0.5rem 1rem;
  width: 25rem;
  font-size: 1.2rem;
  border: none;
  outline: none;
  border-radius: 5px;
  :focus {
    outline: #3c762f;
  }

  @media only screen and (max-width: 600px) {
    width: 70vw;
    padding: 0.5rem;
  }
`;

const SearchButton = styled.div`
  color: white;
  background-color: red;
  padding: 0.5rem 1rem;
  font-size: 1.2rem;
  cursor: pointer;
`;

const Explore = styled.div`
  text-decoration: none;
  position: absolute;
  border: none;
  font-size: 14px;
  font-family: inherit;
  color: #fff;
  width: 9em;
  height: 3em;
  line-height: 2em;
  text-align: center;
  background: linear-gradient(90deg, #03a9f4, #f441a5, #ffeb3b, #03a9f4);
  background-size: 300%;
  border-radius: 30px;
  z-index: 1;
  margin-bottom: 2rem;

  :hover {
    animation: ani 8s linear infinite;
    border: none;
  }
  @keyframes ani {
    0% {
      background-position: 0%;
    }

    100% {
      background-position: 400%;
    }
  }

  :before {
    content: "";
    position: absolute;
    top: -5px;
    left: -5px;
    right: -5px;
    bottom: -5px;
    z-index: -1;
    background: linear-gradient(90deg, #03a9f4, #f441a5, #ffeb3b, #03a9f4);
    background-size: 400%;
    border-radius: 35px;
    transition: 1s;
  }

  :hover::before {
    filter: blur(20px);
  }

`;

export default function Home() {
  const brandImages = [
    { name: Netflix, id: 1 },
    { name: DW, id: 2 },
    { name: MGM, id: 3 },
    { name: Rocky, id: 4 },
    { name: Universal, id: 5 },
    { name: WB, id: 6 },
    { name: Sony, id: 7 },
    { name: Paramount, id: 8 },
  ];
  const router = useRouter();
  const [searchInput, setSearchInput] = useState("");
  const goAndSearch = (value) => {
    if (value === "") {
      alert("Please Provide A Movie Name");
    } else {
      router.push(`search/?query=${value}`);
    }
  };

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="py-md-4">
          <div className="px-4 my-md-5 py-5 h-100">
            <div className="d-md-flex justify-content-md-between flex-xs-column">
              <div className="w-100 mb-4  w-md-50">
                <h1 className="fs-1 mt-5 pt-5" style={{fontFamily: 'Zen Kaku Gothic New, sans-serif'}}>Leave What to Watch To US</h1>
                <p className="fs-5 w-md-75 pb-md-4" style={{fontFamily: 'Zen Kaku Gothic New, sans-serif'}}>
                  Lorem Ipsum has been the industry&apos;s standard dummy text
                  ever since the 1500s, when an unknown printer took a galley of
                  type and scrambled it to make a type specimen book. It has
                  survived not only five centuries.
                </p>
                <Explore
                  type="button"
                  className="btn btn-primary"
                  onClick={() => router.push("/latestmovies")}
                >
                  Explore
                </Explore>
              </div>
              <Image src={Laptop} alt={"Movie-img"} width={800} height={600} />
            </div>
            <div></div>
          </div>
          <h2 className="text-center py-4 mb-3">Movie Brands That Trust Us</h2>
          <div className="d-flex flex-wrap justify-content-center w-100 mx-auto py-2">
            {brandImages.map((m) => {
              return (
                <Image
                  src={m.name}
                  key={m.id}
                  alt={m.name}
                  width={305}
                  height={250}
                  responsive={"100vw"}
                />
              );
            })}
          </div>
        </div>
      </div>
      <SearchSection>
        <div>
          <p className="fs-3">Search For A Movie</p>
        </div>
        <div style={{ display: "flex", justifyContent: "center" }}>
          <Input
            type={"text"}
            placeholder={"Enter Movie Title here"}
            value={searchInput}
            onChange={(e) => setSearchInput(e.target.value)}
          />
          <span>
            <SearchButton type={"btn"} onClick={() => goAndSearch(searchInput)}>
              <i className="bi bi-search"></i>
            </SearchButton>
          </span>
        </div>
      </SearchSection>
    </>
  );
}
